# Generated by Django 4.1.5 on 2023-05-23 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcion', '0001_initial'),
        ('comidas', '0001_initial'),
        ('multiplex_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sillas', models.CharField(max_length=25)),
                ('estado', models.IntegerField()),
                ('comida', models.BooleanField(default=False)),
                ('valor', models.IntegerField()),
                ('funcion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcion.funcion', verbose_name='funcion')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('puntos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('valor', models.IntegerField()),
                ('punto_agil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.punto_agil', verbose_name='punto agil')),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='Venta_snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('snack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comidas.snack', verbose_name='snack')),
                ('venta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.venta', verbose_name='venta')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='snacks',
            field=models.ManyToManyField(blank=True, through='reserva.Venta_snack', to='comidas.snack'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.usuario', verbose_name='usuario'),
        ),
    ]
