# Generated by Django 4.1.5 on 2023-05-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comidas', '0001_initial'),
        ('multiplex_app', '0001_initial'),
        ('cartelera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=12)),
                ('pelicula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.pelicula', verbose_name='pelicula')),
            ],
            options={
                'verbose_name': 'funcion',
                'verbose_name_plural': 'funciones',
                'db_table': 'Funcion',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sillas', models.CharField(max_length=25)),
                ('estado', models.IntegerField()),
                ('funcion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.funcion', verbose_name='funcion')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=40)),
                ('puntos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
                ('punto_agil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.punto_agil', verbose_name='punto agil')),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva', verbose_name='reserva')),
                ('snacks', models.ManyToManyField(db_table='Venta_snack', to='comidas.snack')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('numero_sillas', models.IntegerField(verbose_name='numero de sillas')),
                ('multiplex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.cine', verbose_name='multiplex')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'db_table': 'Sala',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.usuario', verbose_name='multiplex'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='sala_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.sala', verbose_name='sala'),
        ),
    ]
