# Generated by Django 4.1.5 on 2023-05-06 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_remove_sala_numero_sillas_sala_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
