# Generated by Django 4.1.5 on 2023-05-06 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex_app', '0003_alter_cine_ciudad_alter_empleado_cargo'),
        ('reserva', '0004_funcion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='multiplex_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.cine', verbose_name='multiplex'),
        ),
    ]
