# Generated by Django 4.1.5 on 2023-05-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_funcion_multiplex_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sillasdisponibles',
            options={'verbose_name': 'sillas_disponibles', 'verbose_name_plural': 'sillas_disponibles'},
        ),
    ]
