# Generated by Django 4.1.5 on 2023-05-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_alter_sillasdisponibles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comida',
            field=models.BooleanField(default=False),
        ),
    ]
