# Generated by Django 4.1.5 on 2023-05-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcion', '0001_initial'),
        ('reserva', '0007_reserva_comida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='multiplex_id',
        ),
        migrations.RemoveField(
            model_name='sillasdisponibles',
            name='funcion_id',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='funcion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcion.funcion', verbose_name='funcion'),
        ),
        migrations.DeleteModel(
            name='Funcion',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='sillasDisponibles',
        ),
    ]
