# Generated by Django 4.1.5 on 2023-05-12 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multiplex_app', '0004_remove_cine_peliculas'),
        ('cartelera', '0003_pelicula_cines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=12)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('multiplex_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.cine', verbose_name='multiplex')),
                ('pelicula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.pelicula', verbose_name='pelicula')),
            ],
            options={
                'verbose_name': 'funcion',
                'verbose_name_plural': 'funciones',
                'db_table': 'Funcion',
            },
        ),
        migrations.CreateModel(
            name='sillasDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sillas_dispo', models.IntegerField()),
                ('sillas_dispo', models.CharField(max_length=200)),
                ('funcion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcion.funcion', verbose_name='función')),
            ],
            options={
                'verbose_name': 'sillas_disponibles',
                'verbose_name_plural': 'sillas_disponibles',
                'db_table': 'Sillas_disponibles',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.IntegerField(choices=[[1, '1 (50 sillas)'], [2, '2 (60 sillas)'], [3, '3 (70 sillas)']], default=1, verbose_name='tipo de sala')),
                ('multiplex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.cine', verbose_name='multiplex')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'db_table': 'Sala',
            },
        ),
        migrations.AddField(
            model_name='funcion',
            name='sala_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcion.sala', verbose_name='sala'),
        ),
    ]
