# Generated by Django 4.1.5 on 2023-05-25 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multiplex_app', '0001_initial'),
        ('cartelera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=12)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('multiplex_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.cine', verbose_name='multiplex')),
                ('pelicula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.pelicula', verbose_name='pelicula')),
                ('sala_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.sala', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'funcion',
                'verbose_name_plural': 'funciones',
                'db_table': 'Funcion',
            },
        ),
        migrations.CreateModel(
            name='sillasDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sillas_dispo', models.IntegerField()),
                ('sillas_dispo', models.CharField(max_length=200)),
                ('funcion_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcion.funcion', verbose_name='función')),
            ],
            options={
                'verbose_name': 'sillas_disponibles',
                'verbose_name_plural': 'sillas_disponibles',
                'db_table': 'Sillas_disponibles',
            },
        ),
    ]
