# Generated by Django 4.1.5 on 2023-05-12 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillasdisponibles',
            name='funcion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcion.funcion', unique=True, verbose_name='función'),
        ),
    ]
