# Generated by Django 4.1.5 on 2023-05-17 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex_app', '0006_sala'),
        ('funcion', '0002_alter_sillasdisponibles_funcion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='sala_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.sala', verbose_name='sala'),
        ),
        migrations.AlterField(
            model_name='sillasdisponibles',
            name='funcion_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcion.funcion', verbose_name='función'),
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
