# Generated by Django 4.1.5 on 2023-05-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('salas', models.IntegerField()),
                ('ciudad', models.IntegerField(choices=[[1, 'Bogotá D.C.'], [2, 'Medellin'], [3, 'Cali'], [4, 'Baranquilla']])),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'multiplex',
                'verbose_name_plural': 'multiplex',
                'db_table': 'Multiplex',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('cargo', models.IntegerField(choices=[[1, 'Administrador'], [2, 'Empleado']])),
                ('fecha_inicio_cont', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inicio del contrato')),
                ('tiempo_contratado', models.DurationField()),
                ('multiplex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.cine', verbose_name='multiplex')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.IntegerField(choices=[[1, '1 (50 sillas)'], [2, '2 (60 sillas)'], [3, '3 (70 sillas)']], default=1, verbose_name='tipo de sala')),
                ('multiplex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.cine', verbose_name='multiplex')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'db_table': 'Sala',
            },
        ),
        migrations.CreateModel(
            name='Punto_agil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=12)),
                ('empleado_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.empleado', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'punto agil',
                'verbose_name_plural': 'puntos agiles',
                'db_table': 'Punto_agil',
            },
        ),
    ]
