# Generated by Django 4.1.5 on 2023-05-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex_app', '0002_alter_empleado_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='ciudad',
            field=models.IntegerField(choices=[[1, 'Bogotá D.C.'], [2, 'Medellin'], [3, 'Cali'], [4, 'Baranquilla']]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.IntegerField(choices=[[1, 'Administrador'], [2, 'Empleado']]),
        ),
    ]
