# Generated by Django 4.1.5 on 2023-05-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex_app', '0004_remove_cine_peliculas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cine',
            name='snacks',
        ),
    ]
