# Generated by Django 4.1.5 on 2023-05-17 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex_app', '0005_remove_cine_snacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.IntegerField(choices=[[1, '1 (50 sillas)'], [2, '2 (60 sillas)'], [3, '3 (70 sillas)']], default=1, verbose_name='tipo de sala')),
                ('multiplex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex_app.cine', verbose_name='multiplex')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'db_table': 'Sala',
            },
        ),
    ]
