# Generated by Django 4.1.5 on 2023-05-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multiplex_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('clasificacion', models.IntegerField(choices=[[1, 'General'], [2, 'Mayores de 12'], [3, 'Mayores de 15'], [4, 'Mayores de edad']])),
                ('lenguaje', models.IntegerField(choices=[[1, 'Español'], [2, 'Ingles'], [3, 'Japones']])),
                ('fecha_estreno', models.DateField(verbose_name='fecha de estreno')),
                ('puntuacion', models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5']])),
                ('imagen', models.URLField()),
                ('cines', models.ManyToManyField(db_table='Multiplex_pelicula', to='multiplex_app.cine')),
            ],
            options={
                'verbose_name': 'pelicula',
                'verbose_name_plural': 'peliculas',
                'db_table': 'Pelicula',
            },
        ),
    ]
