# Generated by Django 4.1.5 on 2023-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.IntegerField(choices=[[1, 'General'], [2, 'Mayores de 12'], [3, 'Mayores de 15'], [4, 'Mayores de edad']]),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='lenguaje',
            field=models.IntegerField(choices=[[1, 'Español'], [2, 'Ingles'], [3, 'Japones']]),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='puntuacion',
            field=models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5']]),
        ),
    ]
