# Generated by Django 4.1.5 on 2023-05-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex_app', '0004_remove_cine_peliculas'),
        ('cartelera', '0002_alter_pelicula_clasificacion_alter_pelicula_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cines',
            field=models.ManyToManyField(db_table='Multiplex_pelicula', to='multiplex_app.cine'),
        ),
    ]
