# Generated by Django 4.1.5 on 2023-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
                ('imagen', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'snack',
                'verbose_name_plural': 'snacks',
                'db_table': 'Snack',
            },
        ),
    ]
