# Generated by Django 4.1.5 on 2023-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='imagen',
            field=models.URLField(),
        ),
    ]
