# Generated by Django 4.1.5 on 2023-05-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex_app', '0005_remove_cine_snacks'),
        ('comidas', '0002_alter_snack_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='cines',
            field=models.ManyToManyField(db_table='Multiplex_snack', to='multiplex_app.cine'),
        ),
    ]
